// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// Elixir code generation for OTP supervision trees.
// Generates Application, Supervisor, GenServer, mix.exs, and test modules.

use crate::manifest::{to_atom_name, to_module_name, ChildDef, Manifest, SupervisorDef};

/// Generate a mix.exs project file for the Elixir application.
/// Includes the application callback module and standard dependencies.
pub fn generate_mix_exs(manifest: &Manifest) -> String {
    let app_name = to_atom_name(&manifest.workload.name);
    let root_module = extract_root_module(&manifest.workload.entry);

    format!(
        r#"# SPDX-License-Identifier: PMPL-1.0-or-later
# Generated by otpiser — https://github.com/hyperpolymath/otpiser

defmodule {root_module}.MixProject do
  use Mix.Project

  def project do
    [
      app: :{app_name},
      version: "0.1.0",
      elixir: "~> 1.15",
      start_permanent: Mix.env() == :prod,
      deps: deps()
    ]
  end

  def application do
    [
      extra_applications: [:logger],
      mod: {{{root_module}.Application, []}}
    ]
  end

  defp deps do
    []
  end
end
"#
    )
}

/// Generate the Application module with start/2 callback.
/// This is the OTP application entry point that starts the root supervision tree.
pub fn generate_application_module(manifest: &Manifest) -> String {
    let root_module = extract_root_module(&manifest.workload.entry);
    let app_name = to_atom_name(&manifest.workload.name);

    // Build the children list for the root supervisor.
    let children_code = if manifest.supervisors.is_empty() {
        format!("      {{{root_module}.Supervisor, []}}")
    } else {
        manifest
            .supervisors
            .iter()
            .map(|sup| {
                let sup_module = format!(
                    "{}.{}Supervisor",
                    root_module,
                    to_module_name(&sup.name)
                );
                format!("      {{{sup_module}, []}}")
            })
            .collect::<Vec<_>>()
            .join(",\n")
    };

    let strategy = &manifest.workload.strategy;

    format!(
        r#"# SPDX-License-Identifier: PMPL-1.0-or-later
# Generated by otpiser — https://github.com/hyperpolymath/otpiser

defmodule {root_module}.Application do
  @moduledoc """
  OTP Application callback for {app_name}.
  Starts the root supervision tree.
  """

  use Application

  @impl true
  def start(_type, _args) do
    children = [
{children_code}
    ]

    opts = [strategy: :{strategy}, name: {root_module}.RootSupervisor]
    Supervisor.start_link(children, opts)
  end
end
"#
    )
}

/// Generate a default supervisor module when no explicit supervisors are defined.
/// Creates a minimal supervisor with no children as a starting point.
pub fn generate_default_supervisor(manifest: &Manifest) -> String {
    let root_module = extract_root_module(&manifest.workload.entry);
    let strategy = &manifest.workload.strategy;

    format!(
        r#"# SPDX-License-Identifier: PMPL-1.0-or-later
# Generated by otpiser — https://github.com/hyperpolymath/otpiser

defmodule {root_module}.Supervisor do
  @moduledoc """
  Root supervisor for {root_module}.
  Add child specs to the children list below.
  """

  use Supervisor

  def start_link(init_arg) do
    Supervisor.start_link(__MODULE__, init_arg, name: __MODULE__)
  end

  @impl true
  def init(_init_arg) do
    children = []

    Supervisor.init(children, strategy: :{strategy})
  end
end
"#
    )
}

/// Generate a supervisor module from a SupervisorDef.
/// Includes child specs for all defined children with appropriate restart types.
pub fn generate_supervisor_module(manifest: &Manifest, sup: &SupervisorDef) -> String {
    let root_module = extract_root_module(&manifest.workload.entry);
    let sup_module_name = to_module_name(&sup.name);
    let full_module = format!("{}.{}Supervisor", root_module, sup_module_name);

    // Build child specs.
    let children_code = if sup.children.is_empty() {
        String::from("    children = []")
    } else {
        let specs: Vec<String> = sup
            .children
            .iter()
            .map(|child| generate_child_spec(root_module, child))
            .collect();
        format!("    children = [\n{}\n    ]", specs.join(",\n"))
    };

    format!(
        r#"# SPDX-License-Identifier: PMPL-1.0-or-later
# Generated by otpiser — https://github.com/hyperpolymath/otpiser

defmodule {full_module} do
  @moduledoc """
  Supervisor: {sup_module_name}
  Strategy: {strategy}
  Max restarts: {max_restarts} in {max_seconds}s
  """

  use Supervisor

  def start_link(init_arg) do
    Supervisor.start_link(__MODULE__, init_arg, name: __MODULE__)
  end

  @impl true
  def init(_init_arg) do
{children_code}

    Supervisor.init(children, strategy: :{strategy}, max_restarts: {max_restarts}, max_seconds: {max_seconds})
  end
end
"#,
        strategy = sup.strategy,
        max_restarts = sup.max_restarts,
        max_seconds = sup.max_seconds,
    )
}

/// Generate a child spec entry for use inside a supervisor's init/1.
/// Handles both worker and nested supervisor children, including restart type.
fn generate_child_spec(root_module: &str, child: &ChildDef) -> String {
    let child_module = if let Some(ref module) = child.module {
        format!("{}.{}", root_module, module)
    } else {
        format!("{}.{}", root_module, to_module_name(&child.name))
    };

    let restart_atom = to_atom_name(&child.restart);
    let id_atom = to_atom_name(&child.name);

    if child.child_type == "supervisor" {
        // Supervisor children use Supervisor.child_spec/2 with type: :supervisor.
        format!(
            "      Supervisor.child_spec({{{child_module}, []}}, id: :{id_atom}, restart: :{restart_atom}, type: :supervisor)"
        )
    } else {
        // Worker children with restart type override.
        if child.restart == "permanent" {
            // Permanent is the default, so a simpler spec suffices.
            format!("      {{{child_module}, []}}")
        } else {
            format!(
                "      Supervisor.child_spec({{{child_module}, []}}, id: :{id_atom}, restart: :{restart_atom})"
            )
        }
    }
}

/// Generate a GenServer worker module from a ChildDef.
/// Provides the standard GenServer callbacks: init, handle_call, handle_cast, handle_info.
pub fn generate_worker_module(manifest: &Manifest, child: &ChildDef) -> String {
    let root_module = extract_root_module(&manifest.workload.entry);
    let child_module = if let Some(ref module) = child.module {
        format!("{}.{}", root_module, module)
    } else {
        format!("{}.{}", root_module, to_module_name(&child.name))
    };

    format!(
        r#"# SPDX-License-Identifier: PMPL-1.0-or-later
# Generated by otpiser — https://github.com/hyperpolymath/otpiser

defmodule {child_module} do
  @moduledoc """
  GenServer worker: {name}
  Restart: {restart}
  """

  use GenServer

  ## Client API

  @doc "Start the {name} worker, linking to the caller."
  def start_link(init_arg) do
    GenServer.start_link(__MODULE__, init_arg, name: __MODULE__)
  end

  ## Server Callbacks

  @impl true
  def init(init_arg) do
    {{:ok, %{{args: init_arg}}}}
  end

  @impl true
  def handle_call(_request, _from, state) do
    {{:reply, :ok, state}}
  end

  @impl true
  def handle_cast(_request, state) do
    {{:noreply, state}}
  end

  @impl true
  def handle_info(_msg, state) do
    {{:noreply, state}}
  end
end
"#,
        name = child.name,
        restart = child.restart,
    )
}

/// Generate test_helper.exs for ExUnit bootstrap.
pub fn generate_test_helper() -> String {
    r#"# SPDX-License-Identifier: PMPL-1.0-or-later
# Generated by otpiser — https://github.com/hyperpolymath/otpiser

ExUnit.start()
"#
    .to_string()
}

/// Generate an ExUnit test file that verifies the supervision tree starts correctly.
pub fn generate_test_file(manifest: &Manifest) -> String {
    let root_module = extract_root_module(&manifest.workload.entry);
    let app_name = to_atom_name(&manifest.workload.name);
    let test_module = format!("{}Test", root_module);

    // Build assertions for each supervisor.
    let supervisor_assertions = if manifest.supervisors.is_empty() {
        format!(
            r#"    test "default supervisor is defined" do
      assert Code.ensure_loaded?({root_module}.Supervisor)
    end"#
        )
    } else {
        manifest
            .supervisors
            .iter()
            .map(|sup| {
                let sup_module = format!(
                    "{}.{}Supervisor",
                    root_module,
                    to_module_name(&sup.name)
                );
                format!(
                    r#"    test "{name} supervisor module is defined" do
      assert Code.ensure_loaded?({sup_module})
    end"#,
                    name = sup.name,
                )
            })
            .collect::<Vec<_>>()
            .join("\n\n")
    };

    format!(
        r#"# SPDX-License-Identifier: PMPL-1.0-or-later
# Generated by otpiser — https://github.com/hyperpolymath/otpiser

defmodule {test_module} do
  use ExUnit.Case, async: true

  describe "{app_name} supervision tree" do
    test "application module is defined" do
      assert Code.ensure_loaded?({root_module}.Application)
    end

{supervisor_assertions}
  end
end
"#
    )
}

/// Generate .formatter.exs for consistent Elixir code formatting.
pub fn generate_formatter() -> String {
    r#"# SPDX-License-Identifier: PMPL-1.0-or-later
# Generated by otpiser — https://github.com/hyperpolymath/otpiser

[
  inputs: ["{config,lib,test}/**/*.{ex,exs}"]
]
"#
    .to_string()
}

/// Extract the root module name from an entry like "MyApp.Application".
/// Returns the first segment (e.g., "MyApp") or the full entry if no dot.
fn extract_root_module(entry: &str) -> &str {
    // Find the last dot-separated segment that is "Application" and strip it.
    if let Some(pos) = entry.rfind(".Application") {
        &entry[..pos]
    } else if let Some(pos) = entry.rfind('.') {
        &entry[..pos]
    } else {
        entry
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Verify extract_root_module strips ".Application" suffix correctly.
    #[test]
    fn test_extract_root_module() {
        assert_eq!(extract_root_module("MyApp.Application"), "MyApp");
        assert_eq!(extract_root_module("Deep.Nested.Application"), "Deep.Nested");
        assert_eq!(extract_root_module("MyApp"), "MyApp");
    }
}
